name: "Build Verification"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# --- ADD THIS BLOCK ---
permissions:
  contents: read
# ----------------------

jobs:
  build:
    name: Build App
    runs-on: macos-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Build App
        env:
          scheme: "Bye"
        run: |
          xcodebuild clean build \
            -scheme "$scheme" \
            -destination "platform=macOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
